### ISSUE TITLE
Widget does not loading | Safari, os X

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#107]
**Device:** iMac
**OS:** os X
**Browser:** Safari 
**Link:** http://sarine-widgets.ho.ua/dist/release_w1.5.html
**Version:** 1.1.7

---

#### Steps to reproduce

1. open http://sarine-widgets.ho.ua/dist/release_w1.5.html

#### Actual result

Widget does not loading

#### Expected result

widget should work

![2015-04-24_16-47-06](https://cloud.githubusercontent.com/assets/10975093/7322394/7382813e-eab0-11e4-84ed-b13b8ec81306.png)

**Comment by a-kolomiets** [comment]
Fatal error on Safari: sarine.viewer.manager.js component fails. Screenshot: https://eus1-api.asm.skype.com/v1/objects/0-eus-d3-4a8416a85f8785c2f251263b1effbcb6/views/imgo

**Comment by adica** [comment]
@v-lebedenko 
please fix the URL's

**Comment by a-kolomiets** [comment]
URL's are fixed
