### ISSUE TITLE
Template duplicated in Auto Pager mode of UC browser on iPhone 6

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#12]
**Device:** iPhone 6 
**OS:** iOS 8.1
**Browser:** UC
**Link:** http://api-2.qa.sarine.com/viewer/v1/0EXAMPLE0/0EXECUTE0#
**Version:** 1.0.1

---

#### Steps to reproduce
http://api-2.qa.sarine.com/viewer/v1/0EXAMPLE0/0EXECUTE0#

#### Actual result
Template duplicated 

#### Expected result
templates should not be duplicated

![2015-02-27_17-41-58](https://cloud.githubusercontent.com/assets/10975093/6439771/e70beede-c0de-11e4-9d25-90db6250670e.png)

**Comment by a-kolomiets** [comment]
Cannot reproduce
