### ISSUE TITLE
Change "conditions" link to work with new API method

### ISSUE THREAD

**Issue by adica** [SarineTechnologies/sarine.viewer.templates#128]
change "conditions" link to work with new API method like this:

$('#tnc').on('click',function(){
     GetLegalConditions()
});

instead of hard-coded link

**Comment by adica** [comment]
Need to be forwarded to Yoav sherf and shmulik.
Akiva instrumented to keep working with the explicit hard coded link

**Comment by rotemkli** [comment]
Why was this closed?

**Comment by rotemkli** [comment]
reopen and keep open. api call is not used.
