### ISSUE TITLE
work with new "cut2d v2" instead of "cut2d v1" on 1.9,1.10 templates

### ISSUE THREAD

**Issue by adica** [SarineTechnologies/sarine.viewer.templates#139]
![cut2d](https://cloud.githubusercontent.com/assets/12221686/7567479/eac0f002-f805-11e4-9e9d-e11008ed30bf.png)

**Comment by rotemkli** [comment]
Instead of:
<sarine-viewer viewer="cut2DView"></sarine-viewer>

use:
<sarine-viewer viewer="cut2DView" version="v2"></sarine-viewer>

**Comment by rotemkli** [comment]
Instead of:
<sarine-viewer viewer="cut2DView"></sarine-viewer>

use:
<sarine-viewer viewer="cut2DView" version="v2"></sarine-viewer>

**Comment by rotemkli** [comment]
instead of:
<sarine-viewer viewer="cut2DView"></sarine-viewer>
use:
<sarine-viewer viewer="cut2DView" version="v2"></sarine-viewer>

**Comment by adica** [comment]
![svg](https://cloud.githubusercontent.com/assets/10796525/7670489/46e2e216-fcaf-11e4-8611-38e5ec9a65f6.png)
working example:
http://api.sarine.com/viewer/v1/1TWHN24YJ0/SVGTEST
