### ISSUE TITLE
Viewer does not appear | QA environment

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#147]
**Device:** PC, mobile devices
**OS:** iOS ver.; Windows ver.; os X ver.
**Browser:** Opera(Mini, enabled compressing, disabled compressing), Chrome(40, 41 beta, 42 dev), FF (35, 36 Beta, 37 Aurora), IE(10, 11), UC, Safari (8.0.3.).
**Link:** http://api-2.qa.sarine.com/viewer/v1/197MV9W03H/1EXECUTE6
**Version:** 1.6.2

---

#### Steps to reproduce

1. open http://api-2.qa.sarine.com/viewer/v1/197MV9W03H/1EXECUTE6

#### Actual result

Viewer does not appear

#### Expected result

viewer should be displayed

![tab2](https://cloud.githubusercontent.com/assets/10975093/7627631/04b0c262-fa22-11e4-92fe-e362c244a267.png)

**Comment by adica** [comment]
@v-lebedenko 
use different stone:
http://api-2.qa.sarine.com/viewer/v1/1ESVG7YIFW/1EXECUTE6
