### ISSUE TITLE
Widget does not have to change orientation | FF ; IE

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#149]
**Device:** PC
**OS:** Windows, os X
**Browser:** FF ; IE
**Link:** https://api.sarine.com/viewer/v1/1F0QV3N1IC/3AMCYEKZR3
**Version:** 1.3

---

#### Steps to reproduce

 1. Launch the site https://api.sarine.com/viewer/v1/1F0QV3N1IC/3AMCYEKZR3
2. Tap on Light and open all the sub-links by clicking ? mark
3. Close all the sub-links pages by clicking X
4. Tap on Loupe (on the scale bar)
5. Tap on the diamond
6. Click side arrow button and top arrow button (diamond will change upon clicking the buttons)
7. After multiple clicks, tap the "Tab" button on the keyboard
8. Now click the side scroll bar to top
9. Tap Shift+tab button and observe

#### Actual result

Wrong widget behavior. Screenshot attached

#### Expected result

Widget does not have to change orientation

![tab bug](https://cloud.githubusercontent.com/assets/10975093/7630252/e41afce6-fa3c-11e4-9aae-f466e937a87c.jpg)

**Comment by rotemkli** [comment]
Status?

**Comment by v-lebedenko** [comment]
Problem is solved. We are testing now
