### ISSUE TITLE
Widget does not open | Opera Turbo | iPad

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#153]
**Device:** iPad
**OS:** 8.2
**Browser:** Opera Turbo 
**Link:** http://api-2.qa.sarine.com/viewer/v1/WLLQ0BET7/1EXECUTE16
**Version:** 1.16

---

#### Steps to reproduce

1. open http://api-2.qa.sarine.com/viewer/v1/WLLQ0BET7/1EXECUTE16 in Opera Turbo

#### Actual result

Widget does not open

#### Expected result

widget should open

![2015-05-15_11-35-43](https://cloud.githubusercontent.com/assets/10975093/7651397/a62e4e7a-fb08-11e4-9b21-ac96e6e37b28.png)

**Comment by rotemkli** [comment]
why does Opera turbo being checked?

**Comment by rotemkli** [comment]
Is it not the Opera turbo known issue?
