### ISSUE TITLE
Crash browser after click "Play" button | iPhone 4s / Chrome

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#165]
**Device:** iPhone 4s
**OS:** iOS 8.2
**Browser:** Chrome
**Link:** https://api-2.qa.sarine.com/viewer/v1/2165JRE8F4/1EXECUTE1
**Version:** 1.1
---

#### Steps to reproduce

1. open https://api-2.qa.sarine.com/viewer/v1/2165JRE8F4/1EXECUTE1
2. click "Light"
3. click "Brilliance"
4. increase sub slide
5. click "Play" button

#### Actual result

Crash browser after click "Play" button

#### Expected result

video should be play

![2015-05-25_18-10-05](https://cloud.githubusercontent.com/assets/10975093/7798986/5211516c-0309-11e5-85f2-99ca42fd777d.png)

**Comment by vlad-snrg** [comment]
Fixed
