### ISSUE TITLE
Crash browser after click "Light", "Loupe" or "Hearts & Arrows" in landscape | iPhone 4s

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#167]
Device: iPhone 4s
OS: iOS 8.2
Browser: Chrome, UC, Opera Mini, Safari
Link: http://api-2.qa.sarine.com/viewer/v1/83QDX2HKD7I/1EXECUTE1
Version: 1.1

#### Steps to reproduce

1. open http://api-2.qa.sarine.com/viewer/v1/83QDX2HKD7I/1EXECUTE1
2. change device orientation to landscape
3. click "Light", "Loupe" or "Hearts & Arrows"

#### Actual result

Crash browser after click "Light" (for Chrome, UC, Opera Mini. Safari browser doesn't open this page, screenshot attached )

#### Expected result
Page opens

![img_2260](https://cloud.githubusercontent.com/assets/10975093/7809083/6739f728-03a0-11e5-9f97-52ffe748e11f.PNG)

**Comment by vlad-snrg** [comment]
Fixed
