### ISSUE TITLE
Opera Mini does not open site on iOS device

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#17]
**Device:** mobile devices
**OS:** iOS
**Browser:** Opera mini 
**Link:** http://api-2.qa.sarine.com/viewer/v1/0EXAMPLE0/0EXECUTE0#
**Version:** 1.0.1

---

#### Steps to reproduce
1. open http://api-2.qa.sarine.com/viewer/v1/0EXAMPLE0/0EXECUTE0#  in browser

#### Actual result
site does not open 

#### Expected result
site should be opened

**Comment by adica** [comment]
Not supported browser
