### ISSUE TITLE
Site does not open in Opera (mini; enabled compressing) on Android device

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#18]
**Device:** Android device
**OS:** Android 
**Browser:** Opera (mini; enabled compressing) 
**Link:** open http://api-2.qa.sarine.com/viewer/v1/0EXAMPLE0/0EXECUTE0#
**Version:** 1.0.1

---

#### Steps to reproduce
1. open http://api-2.qa.sarine.com/viewer/v1/0EXAMPLE0/0EXECUTE0# in browser

#### Actual result
Site does not open 

#### Expected result
site should be opened

**Comment by adica** [comment]
Not supported
