### ISSUE TITLE
"Graded by" has wrong position 

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#183]
Device: Samsung Galaxy S4 (portrait orientation)
OS: android
Browser: all
Link: http://api-2.qa.sarine.com/viewer/v1/2165JRE8F4/1EXECUTE2
Version: 1.2
---

#### Steps to reproduce
1. open the link above
2. scroll down this page

#### Actual result
"Graded by" text located above the "Powered by" (screenshot 1). 

Please could you clarify is it correct for mobile version? For desktop version "Conditions", "Graded by" and "Powered by" should be in one line according to design (screenshot 2)
![1](https://cloud.githubusercontent.com/assets/10975093/7980829/64ac8768-0ab3-11e5-9e38-71e36e1a0606.png)
![2](https://cloud.githubusercontent.com/assets/10975093/7980830/64b0c8c8-0ab3-11e5-98a6-c2f4d90d0c9d.png)

**Comment by rotemkli** [comment]
I think it can be closed. IGI is no longer required.
