### ISSUE TITLE
Pictures not displayed in Safari browser

### ISSUE THREAD

**Issue by a-kolomiets** [SarineTechnologies/sarine.viewer.templates#2]
**Device:** iMac
**OS:**  os X
**Browser:**  Safari browser (Version 8.0.3 (10600.3.18)) 
**Link:** http://dev.sarineplatform.com/qa1/content/viewers/index.html#
**Version:** 1.0.1

---

#### Steps to reproduce

1. open http://dev.sarineplatform.com/qa1/content/viewers/index.html# in Safari browser

#### Actual result
pictures not displayed in Safari browser 

#### Expected result
 pictures should be displayed

**Comment by a-kolomiets** [comment]
Adi, 

There is exception in Safari 8.0.3 on Mac OS 10.10.2 

Please see the screenshot.
![2015-02-19_17-17-27](https://cloud.githubusercontent.com/assets/5763168/6437734/f2cdb4f0-c0ca-11e4-90ea-4f7e77097a26.png)
![2015-02-27 15 39 17](https://cloud.githubusercontent.com/assets/5763168/6437735/f2cddf5c-c0ca-11e4-8599-b5123293a98a.png)

**Comment by adica** [comment]
This bug already been solved on QA-2 env:
http://api-2.qa.sarine.com/viewer/v1/1ESVG7YIFW/RWEB4PROD1

**Comment by adica** [comment]
Try on this:
http://dev.sarineplatform.com.s3.amazonaws.com/qa2/content/viewers/templates/0EXECUTE0/index_shell_stub.html

**Comment by adica** [comment]
@v-lebedenko 
did it happens also on the new stub version?
http://dev.sarineplatform.com.s3.amazonaws.com/qa2/content/viewers/templates/0EXECUTE0/index_shell_stub.html

**Comment by v-lebedenko** [comment]
you are right, on these resource pictures displaying
