### ISSUE TITLE
Charts are empty

### ISSUE THREAD

**Issue by a-kolomiets** [SarineTechnologies/sarine.viewer.templates#20]
**Device:** PC
**OS:** Windows 8
**Browser:** Google Chrome 40
**Link:** http://api.sarine.com/viewer/v1/38TUOFZY8S/0EXECUTE0#
**Version:** 1.0.1

---

#### Steps to reproduce
* Open http://api.sarine.com/viewer/v1/38TUOFZY8S/0EXECUTE0#
* Click on ? sign near "Sarine Light Performance Results" at top
* Pop-up dialog will be opened

#### Actual result
* Charts are empty

#### Expected result
* Charts should display some values

**Comment by a-kolomiets** [comment]
Adi,

The issue is that in HTML, the diamond params has an incorrect values.

For example:
  "lightGrades": {
    "brilliance": {
      "value": 40.0,
      **"name": "Brilliance"**
    },

Name should be on of the following values:
MIN, STD, HIGH, VH, EXC according to the gradeScales array.

var gradeScales = 
...
  "brilliance": [
    {
      "order": 1,
      "Name": "MIN",
      "default-display": "Minimum"
    },
    {
      "order": 2,
      "Name": "STD",
      "default-display": "Standard"
    },
    {
      "order": 3,
      "Name": "HIGH",
      "default-display": "High"
    },
    {
      "order": 4,
      "Name": "VH",
      "default-display": "Very high"
    },
    {
      "order": 5,
      "Name": "EXC",
      "default-display": "Exceptional"
    }
  ],

**Comment by adica** [comment]
This is an old and not valid stone  (we will delete it)
please work with this one:
https://api.sarine.com/viewer/v1/23WSWG0C2G/0EXECUTE0

**Comment by a-kolomiets** [comment]
@adica 

The charts are empty on this page as well - https://api.sarine.com/viewer/v1/23WSWG0C2G/0EXECUTE0

I see that the stone properties are no valid as well.

Please advise.

**Comment by adica** [comment]
Why not valid?
"lightGrades": {
    "brilliance": {
      "value": 5.0,
      "name": "Exceptional"
    },
    "symmetry": {
      "value": 5.0,
      "name": "Exceptional"
    },
    "fire": {
      "value": 4.0,
      "name": "Very High"
    },
    "totalGrade": {
      "value": 8.0,
      "name": "Ultimate2"
    },
    "scintillation": {
      "value": 4.0,
      "name": "Very High"
    },
    "rotationAngle": 0.0
  },

**Comment by a-kolomiets** [comment]
@adica 

Because gradeScales array has other values like MIN, STD, HIGH, VH, EXC.

    var gradeScales = {
  "symmetry": [
    {
      "order": 1,
      "Name": "MIN",
      "default-display": "Minimum"
    },
    {
      "order": 2,
      "Name": "STD",
      "default-display": "Standard"
    },
    {
      "order": 3,
      "Name": "HIGH",
      "default-display": "High"
    },
    {
      "order": 4,
      "Name": "VH",
      "default-display": "Very high"
    },
    {
      "order": 5,
      "Name": "EXC",
      "default-display": "Exceptional"
    }
  ],

**Comment by adica** [comment]
@a-kolomiets 
you should take the "order" (number) and find the "name" (text) in the scale

**Comment by a-kolomiets** [comment]
@adica 

You meant that we have to use "value" at lightGrades to find the correct value at gradeScales?

It may be we can use "value" for the Charts if the possible values for "value" are 1, 2, 3, 4, 5 only. Please advise.

**Comment by adica** [comment]
@a-kolomiets 
yes.
I don't know what our product guys want you to show on the grid scale.
the data is valid.
