### ISSUE TITLE
 Items displayes in different order

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#21]
**Device:** PC
**OS:** Windows 7 64bit.
**Browser:** Chrome, IE11
**Link:** http://api.sarine.com/viewer/v1/23WSWG0C2G/RWEB4STG01
**Version:** 1.0.1

---

#### Steps to reproduce
1. open http://api.sarine.com/viewer/v1/23WSWG0C2G/RWEB4STG01 in browser

#### Actual result
 Items displayes in different order
#### Expected result
items should appear in the same order

![0330d5df6da62790c485c8d61ad14e90efa94fa353a3c0b032 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/10975093/6443515/0e966c1a-c100-11e4-96b0-94fd95487dc3.png)

**Comment by adica** [comment]
@a-kolomiets 
I can't control the order of images (it's async call) - so it will can change.
I added classes with image name so you can sort it on page
http://api-2.qa.sarine.com/viewer/v1/0EXAMPLE0/0EXECUTE0

**Comment by v-lebedenko** [comment]
we checked with last template version and everything works in right way
