### ISSUE TITLE
stone scales are not use in 0EXECUTE0 template.

### ISSUE THREAD

**Issue by gadaGit** [SarineTechnologies/sarine.viewer.templates#22]
this template is missing some of the data 
that allows the values from json to be shown in this page:  "Sarine Light Performance Results".

(see example link 2 has the data...)

example link 1:  
http://api-2.qa.sarine.com/viewer/v1/1ESVG7YIFW/0EXECUTE0#
example link 2:  
http://api-2.qa.sarine.com/viewer/v1/1ESVG7YIFW/RWEB4PROD1

maybe these attributes are not in use ? 
<span data-sarine-info="friendlyName"></span><br />
<span data-sarine-info="lightGrades.brilliance.value"></span><br />
<span data-sarine-info="lightGrades.symmetry.value"></span><br />
<span data-sarine-info="lightGrades.fire.value"></span><br />
<span data-sarine-info="lightGrades.totalGrade.value"></span><br />
<span data-sarine-info="lightGrades.scintillation.value"></span><br />

**Comment by a-kolomiets** [comment]
@gadaGit The both links don't work right now. Please advise.

**Comment by a-kolomiets** [comment]
![2015-03-02_17-56-11](https://cloud.githubusercontent.com/assets/5763168/6444379/e34e9aae-c105-11e4-8686-bcee5f0cbb14.png)

**Comment by a-kolomiets** [comment]
@gadaGit 

I see that URLs work but there is no template for them. Also, I think that we resolved the issue with charts already. Please can you double check this issue with the latest template - http://dev.sarineplatform.com/qa2/content/viewers/templates/0EXECUTE0/v1.0.2/index.html

**Comment by a-kolomiets** [comment]
@gadaGit 
Please deploy the latest code to   http://d3oayecwxm3wp6.cloudfront.net/qa4/content/viewers/templates/AAAAAAAAAA/v1/index.html

**Comment by a-kolomiets** [comment]
Not actual
