### ISSUE TITLE
Wrong behavior on clicking "?"

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#24]
**Device:** Samsung galaxy s3
**OS:** android
**Browser:** native
**Link:** http://mobile.synergetica.co/sarine/index.html
**Version:** 1.0.1

---

#### Steps to reproduce
1. Open http://mobile.synergetica.co/sarine/index.html in browser
2. Click any "?"

#### Actual result
black square flickers 

#### Expected result
need to remove black square

![2015-03-03_11-19-13](https://cloud.githubusercontent.com/assets/10975093/6461414/6e55fdc0-c1a8-11e4-9fbc-86cd5a34e736.png)

**Comment by a-kolomiets** [comment]
It's a known issue of webkit engine.
https://code.google.com/p/chromium/issues/detail?id=142038
