### ISSUE TITLE
Template does not work correctly

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#26]
**Device:** mobile devices
**OS:** iOS, Android
**Browser:** Opera, Safari, UC, Chrome
**Link:** http://mobile.synergetica.co/sarine/index.html
**Version:** 1.0.1

---

#### Steps to reproduce
1. open http://mobile.synergetica.co/sarine/index.html
2. swipe screen from the left to the right few times

#### Actual result

Template works not correctly (screenshot)

#### Expected result
template should work correctly

![2015-03-04_9-27-47](https://cloud.githubusercontent.com/assets/10975093/6479886/205c6ab6-c255-11e4-958a-0877a6097356.png)

**Comment by a-kolomiets** [comment]
Abnormal user behavior
