### ISSUE TITLE
H&A images are not In the current size

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#33]
**Device:** PC, mobile devices
**OS:** iOS ver.; Windows ver.; os X ver.
**Browser:** Opera(Mini, enabled compressing, disabled compressing), Chrome(40, 41 beta, 42 dev), FF (35, 36 Beta, 37 Aurora), IE(10, 11), UC, Safari (8.0.3.).
**Link:** http://mobile.synergetica.co/sarine/index.html
**Version:** 1.0.1

---

#### Steps to reproduce

1. open http://mobile.synergetica.co/sarine/index.html
2. click Hearts & Arrows 

#### Actual result

images are not In the current size

#### Expected result

screenshot attached

![2015-03-06_18-06-52](https://cloud.githubusercontent.com/assets/10975093/6529071/ec9b620a-c42e-11e4-8518-f44ab92bc777.png)
![2015-03-06_18-06-12](https://cloud.githubusercontent.com/assets/10975093/6529072/eca0077e-c42e-11e4-8fc8-28f9961c313c.png)

**Comment by a-kolomiets** [comment]
It's a design issue.
