### ISSUE TITLE
After window was maximize picture change orientation

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#34]
**Device:** Samsung Galaxy Tab 2 (7')											
**OS:** android
**Browser:** UC
**Link:** http://mobile.synergetica.co/sarine/index.html
**Version:** 1.0.1

---

#### Steps to reproduce

1. open http://mobile.synergetica.co/sarine/index.html
2. we are increasing template

#### Actual result

 picture change orientation

#### Expected result

picture shouldn't change orientation

![screenshot_2015-03-06-19-23-28](https://cloud.githubusercontent.com/assets/10975093/6530157/2fef269c-c437-11e4-91da-7d97dfd9c052.png)

**Comment by a-kolomiets** [comment]
Abnormal user behavior
