### ISSUE TITLE
Template does not work properly in Windows 7,8 ( IE10, 11)

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#36]
**Device:** PC
**OS:** Windows 7
**Browser:** IE 10, 11
**Link:** http://mobile.synergetica.co/sarine/index.html
**Version:** 1.0.1

---

#### Steps to reproduce
1. open http://mobile.synergetica.co/sarine/index.html in browser (screenshot)
2. reload your browser (screenshot)

#### Actual result
Template does not work properly (screenshot)

#### Expected result
template should display properly

![2015-03-16_14-22-15](https://cloud.githubusercontent.com/assets/10975093/6666099/99a8ea50-cbe9-11e4-9a02-e21a4622fecc.png)

![2015-03-16_14-38-59](https://cloud.githubusercontent.com/assets/10975093/6666181/88e9ba90-cbea-11e4-8491-84cbf3d1951e.png)

**Comment by adica** [comment]
![hna](https://cloud.githubusercontent.com/assets/10796525/6884614/c80cedaa-d603-11e4-9489-ec07e9655f12.jpg)
