### ISSUE TITLE
Memory leak in PC browser

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#37]
**Device:** PC
**OS:** os X
**Browser:** Chrome 
**Link:** http://mobile.synergetica.co/sarine/index.html
**Version:** 1.0.1

---

#### Steps to reproduce
1. Open http://mobile.synergetica.co/sarine/index.html in browser

#### Actual result

Memory leak

#### Expected result

memory leak should not be

![2015-03-17_10-41-00](https://cloud.githubusercontent.com/assets/10975093/6683813/8390bc2a-cc93-11e4-86e0-2a1aa39de19b.png)

**Comment by adica** [comment]
solved (in QA)
https://api-2.qa.sarine.com/viewer/v1/0EXAMPLE0/0EXECUTE0

**Comment by adica** [comment]
solved
