### ISSUE TITLE
There is another image at the design on the Profile to actual proportions page

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#5]
you can use the “externalImage” viewer for any other image like this.

![2015-02-23_11-23-11](https://cloud.githubusercontent.com/assets/10975093/6439333/6f7f3f6e-c0da-11e4-8544-2a282e2393f9.png)
![2015-02-23_11-21-32](https://cloud.githubusercontent.com/assets/10975093/6439332/6f7ed0b0-c0da-11e4-91f9-afb35dafd566.png)

**Comment by a-kolomiets** [comment]
Not a bug
