### ISSUE TITLE
Crash of the browser after template increasing

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#55]
**Device:** iPhone 4s
**OS:** iOS 8.1
**Browser:** Opera (Tubro), UC, Chrome
**Link:** http://dev.sarineplatform.com/dev3/content/viewers/templates/0EXECUTE0/v2.0.1/index.html#
**Version:** 2.0.1

---

#### Steps to reproduce

1. open http://dev.sarineplatform.com/dev3/content/viewers/templates/0EXECUTE0/v2.0.1/index.html#
2. increase template 

#### Actual result

Crash of the browser after template increasing

#### Expected result

browser should work stably

**Comment by a-kolomiets** [comment]
It's a sarine vewer performance issue.

**Comment by adica** [comment]
@a-kolomiets 
Please try it without your template and see how it act:
http://api-3.dev.sarine.com/viewer/v1/0EXAMPLE0/0BRINKS01

**Comment by vlad-snrg** [comment]
Fixed
