### ISSUE TITLE
Template changes location after refresh page

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#56]
**Device:** iPhone 4s, 5
**OS:** iOS 8.1
**Browser:** Safari
**Link:** http://dev.sarineplatform.com/dev3/content/viewers/templates/0EXECUTE0/v2.0.1/index.html#
**Version:** 2.0.1

---

#### Steps to reproduce

1. open http://dev.sarineplatform.com/dev3/content/viewers/templates/0EXECUTE0/v2.0.1/index.html#
2. increasing template
3. refresh page in browser 

#### Actual result

Template changes location after refresh page

#### Expected result

template should not change location after refresh page

![2015-04-01_16-41-08](https://cloud.githubusercontent.com/assets/10975093/6942389/eda43c10-d88f-11e4-943e-f0b4707336f9.png)

**Comment by a-kolomiets** [comment]
Not actual
