### ISSUE TITLE
"Light" - Total Grade text is missing.

### ISSUE THREAD

**Issue by gadaGit** [SarineTechnologies/sarine.viewer.templates#63]
the total grade in the light viewer needs to show the "name" from the Json.
![totalgrade](https://cloud.githubusercontent.com/assets/11270338/6960817/a19845ba-d92e-11e4-9ede-ce16e712de22.jpg)

sample stone:
https://api.sarine.com/viewer/v1/2ZID6EX0IW

**Comment by adica** [comment]
@a-kolomiets  always use the "name" key (not "value" key)
