### ISSUE TITLE
When loupe measure= null the "noStone" img is not centered 

### ISSUE THREAD

**Issue by gadaGit** [SarineTechnologies/sarine.viewer.templates#64]
the no stone image needs to be centered 

example stone:
https://api.sarine.com/viewer/v1/38UGH8XXUQ/

![notcenterd](https://cloud.githubusercontent.com/assets/11270338/6960895/2c5698fa-d92f-11e4-87d4-7a4521f0a4d8.jpeg)

**Comment by adica** [comment]
@a-kolomiets notice -this is because the no_stone image is smaller then the original viewer size.
