### ISSUE TITLE
the template loading is very heavy due to Video's embedded in the first page.

### ISSUE THREAD

**Issue by gadaGit** [SarineTechnologies/sarine.viewer.templates#71]
the videos are loaded on first Hit instead of (maybe) by demand/click...

https://api.sarine.com/viewer/v1/2ZID6EX0IW

**Comment by a-kolomiets** [comment]
@gadaGit Please clarify this issue.

Thanks!

**Comment by adica** [comment]
![videos](https://cloud.githubusercontent.com/assets/10796525/6963108/b757dfe0-d943-11e4-90bd-77e74e073374.png)
