### ISSUE TITLE
Crash of the UC browser after template was open (Note 4)

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#75]
**Device:** Note 4
**OS:** android
**Browser:** UC
**Link:** http://dev.sarineplatform.com/dev3/content/viewers/templates/0EXECUTE0/v2-dev/index.html
**Version:** 1.1.5

---

#### Steps to reproduce

1. open http://dev.sarineplatform.com/dev3/content/viewers/templates/0EXECUTE0/v2-dev/index.html
2. swipe menu
3. click any button

#### Actual result

Crash of the UC browser 

#### Expected result

application should work stably

**Comment by a-kolomiets** [comment]
It's a sarine performance issue.

**Comment by adica** [comment]
@a-kolomiets  
Please try it without your template and see how it act:
http://api-3.dev.sarine.com/viewer/v1/0EXAMPLE0/0BRINKS01

**Comment by v-lebedenko** [comment]
Cannot Reproduce
