### ISSUE TITLE
3d viewer loads about 30-60 sec.

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#89]
**Device:** PC
**OS:** Windows 8.1
**Browser:** Chrome
**Link:** http://dev.sarineplatform.com/dev3/content/viewers/templates/0EXECUTE0/v3-dev/w1/index.html
**Version:** 1.1.7

---

#### Steps to reproduce

1. open http://dev.sarineplatform.com/dev3/content/viewers/templates/0EXECUTE0/v3-dev/w1/index.html in browser

#### Actual result

3d viewer loads about  30sec - 1 min. 

#### Expected result

loading time should be about 5 sec. 

![nmyfnk1whsm](https://cloud.githubusercontent.com/assets/10975093/7257867/4fc6e010-e861-11e4-8540-2bbdb82853ae.jpg)

**Comment by adica** [comment]
@a-kolomiets  
you can use 
viewr_0_loupe3DFullInspection_first_init 
event to show the viewer.
don't wait until
viewr_0_loupe3DFullInspection_full_init
